version: '3.8'

services:
  # Esta es la parte de la BBDD
  mysqldb:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

  # Esta es la parte del backend
  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]

  # Esta es la parte del frontend
  client:
    build:
      context: ./$WEB_NAME   #Cambiar aqui para cambiar la web
    ports:
      - $WEB_LOCAL_PORT:$WEB_DOCKER_PORT
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "start"]
